### ISSUE TITLE
Passing additional parameters to the find method

### ISSUE THREAD

**Issue by gabrielhase** [marcbachmann/find-in-batches#2]
Currently, it seems to be intentionally forbidden to pass additional parameters to the find method. Currying is excluded by an assertion and the options hash is defined by the findInBatches code.

IMO this is quite a shortcoming. It is very well possible that the need arises to pass additonal parameters to the find method, e.g., when running it in a for loop of some parameter. Is there anything planned to support passing parameters to the find method?

**Comment by marcbachmann** [comment]
nope. please just wrap the find method.

```
findInBatches(function (options, cb) {
  yourFindMethod({limit: options.limit, offset: options.offset}, yourparams, cb)
}, forEach, function(err){
    if (err) return console.error('Failed to load the entries', err)
    console.log('Loaded all the entries')
});
```
